# Generated by Django 2.2 on 2021-09-01 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('location', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('is_entrance', models.BooleanField(default=True)),
                ('is_using', models.BooleanField(default=True)),
                ('last_alert_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('temperature', models.FloatField()),
                ('time', models.DateTimeField()),
                ('is_blacklist', models.BooleanField(default=True)),
                ('to_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatechecker.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('gate_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('to_building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatechecker.Building')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='to_gate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatechecker.Gate'),
        ),
        migrations.AddField(
            model_name='building',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gatechecker.User'),
        ),
    ]
